<?php

namespace Application\UserBundle\Entity\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserNotifications($userId, $first, $count)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT un, n
                           FROM ApplicationUserBundle:UserNotification un
                           JOIN un.notification n
                           WHERE un.user = :userId")
            ->setParameter('userId', $userId)
            ->setFirstResult($first)
            ->setMaxResults($count)
            ->getResult();
    }
}
