<?php

namespace Application\UserBundle\Entity\Repository;

/**
 * NotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserNotifications($userId, $first, $count)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT un, n
                           FROM ApplicationUserBundle:UserNotification un
                           JOIN un.notification n
                           WHERE un.user = :userId
                           ORDER BY n.created DESC")
            ->setParameter('userId', $userId)
            ->setFirstResult($first)
            ->setMaxResults($count)
            ->getResult();
    }

    public function setAsReadAllNotifications($userId)
    {
        return $this->getEntityManager()
            ->createQuery("UPDATE ApplicationUserBundle:UserNotification un
                           SET un.isRead = true
                           WHERE un.user = :userId")
            ->setParameter('userId', $userId)
            ->execute();
    }

    public function findUserNotification($id)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT un, n, uns
                           FROM ApplicationUserBundle:UserNotification un
                           JOIN un.notification n
                           LEFT JOIN n.userNotifications uns
                           WHERE un.id = :id")
            ->setParameter('id', $id)
            ->getOneOrNullResult();
    }
}
