<?php

namespace AppBundle\Repository;

/**
 * ArturRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArturRepository extends \Doctrine\ORM\EntityRepository
{
}
