<?php

namespace AppBundle\Repository;

/**
 * PlaceTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
