imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
          gc_probability: 0
          save_path: ~
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

doctrine:
    dbal:
        dbname: "%test_database_name%"
twig:
    globals:
        env_prefix: ~