imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    languages:
       en: English
       ru: Русский
    tablet:
        with: 640
        height: 640
    mobile:
        with: 480
        height: 320
    list:
        with: 770
        height: 540
    cover:
        with: 1280
        height: 720

    # event for google analytics
    event_add_goal: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Goal&ea=Add&el=Add%%20goal'
    event_done_goal: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Goal&ea=Done&el=Done%%20goal'
    event_create_goal: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Goal&ea=Create&el=Create%%20goal'
    event_remove_goal: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Goal&ea=Remove&el=Remove%%20goal'
    event_create_story: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Success%%20story&ea=Create&el=Create%%20story'
    event_login_user: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Login&el=Login'
    event_facebook_login_user: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Login&el=Facebook%%20login'
    event_google_login_user: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Login&el=Google%%20login'
    event_twitter_login_user: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Login&el=Twitter%%20login'
    event_user_registration: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Registration&el=Registration'
    event_facebook_registration: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Registration&el=Facebook%%20registration'
    event_google_registration: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Registration&el=Google%%20registration'
    event_twitter_registration: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=User&ea=Registration&el=Twitter%%20registration'
    event_unlist_goal: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Goal&ea=Unlist&el=Unlist%%20goal'
    event_comment: 'https://www.google-analytics.com/collect?v=1&t=event&tid=%ga_id%&cid=%google_client_id%&ec=Comment&ea=Add&el=Add%%20comments'

framework:
    esi:            { enabled: true }
    fragments:      { path: /_proxy }
    translator:      { fallbacks: ["%locale%"] }
    ide: "phpstorm://open?file=%%f&line=%%l"
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v310
        #assets_version: SomeVersionScheme
    default_locale:  en
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
#        cookie_lifetime: 86400
#        gc_maxlifetime: 1800
#        handler_id:  ~
        gc_probability: 0
        save_path: ~
    fragments:       ~
    http_method_override: true

#        gc_maxlifetime: 50 #50 seconds - only needed for testing. Dont use this in a production environment
#        gc_probability: 1 #only needed for testing. Dont use this in a production environment
#        gc_divisor: 1 #only needed for testing. Dont use this in a production environment

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: [ 'AppBundle:Form:multipleFile.html.twig', 'AppBundle:Form:location.html.twig', 'AppBundle:Form:multipleVideo.html.twig', 'A2lixTranslationFormBundle::default.html.twig', 'SonataCoreBundle:Form:datepicker.html.twig']

    globals:
        project_name: %project_name%
        ga_id: %ga_id%


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle, FOSCommentBundle]
    #java: /usr/bin/java
    filters:
        uglifyjs2:
            # the path to the uglifyjs executable
            bin: "%kernel.root_dir%/Resources/node_modules/bin/uglifyjs"
        uglifycss:
            bin: "%kernel.root_dir%/Resources/node_modules/bin/uglifycss"
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
#        yui_css:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
#        yui_js:
#            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        entity_listener_resolver: bl.settings.listener.resolver
        default_entity_manager: default
        result_cache_driver: apc
        query_cache_driver: apc

        dql:
            datetime_functions:
                date:           Oro\ORM\Query\AST\Functions\SimpleFunction
            numeric_functions:
                timestampdiff:  Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
        filters:
            # An array of filters
            publish_filter:
                class:                AppBundle\Filter\PublishFilter
                enabled:              false
            archived_goal_filter:
                class:                AppBundle\Filter\ArchivedGoalFilter
                enabled:              true

        mappings:
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport:  "%mailer_transport%"
    host:       "%mailer_host%"
    username:   "%mailer_user%"
    password:   "%mailer_password%"
    spool:     { type: memory }


#    fos user bundle
fos_user:
    service:
        mailer: bl.user.mailer
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\UserBundle\Entity\User
    registration:
            form:
                type: bl_user_registration
                handler: bl_user.form.handler.registration
    resetting:
        email:
            template: FOSUserBundle:Resetting:email.html.twig

    from_email:
        address: "info@%project_name%.com"
        sender_name: "%project_name%"


# fos comment bundle
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\CommentBundle\Entity\Comment
            thread: Application\CommentBundle\Entity\Thread
    service:
        sorting:
            default: date_asc

# fos rest bundle
fos_rest:
    param_fetcher_listener: true
    body_listener: false
    body_converter:
                enabled: true
    format_listener: false
    view:
        view_response_listener: true
    routing_loader:
        default_format: json
        include_format: false

#    hwi oauth configs
hwi_oauth:
    firewall_name: main
    resource_owners:
            facebook:
                type:                facebook
                client_id:           "%facebook_client_id%"
                client_secret:       "%facebook_client_secret%"
                scope:               "public_profile user_friends email"
                infos_url:           "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,birthday,picture"
            google:
                type:                google
                client_id:           "%google_client_id%"
                client_secret:       "%google_client_secret%"
                scope:               "email profile"
            twitter:
                type:                twitter
                client_id:           "%twitter_client_id%"
                client_secret:       "%twitter_client_secret%"

# sonata block configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

# sonata admin configuration
sonata_admin:
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

# stfo doctrine extensions
stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            loggable: true
            blameable: true

# tinumce
stfalcon_tinymce:
    include_jquery:       false
    tinymce_jquery:       false
    language: en
    theme:
          # Simple theme: same as default theme
          simple:
               plugins:
                   - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                   - "searchreplace wordcount visualblocks visualchars code fullscreen"
                   - "insertdatetime media nonbreaking save table contextmenu directionality"
                   - "emoticons template paste textcolor"
               toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
               toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
               image_advtab: true

a2lix_translation_form:
    locales: [en, ru]                       # [Optionnal] Array of translations locales. Can be specified in the form.
    default_required: false

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        goal_list_small:
            quality: 100
            filters:
                central_crop: { size: [370, 230] }

        goal_list_horizontal:
            quality: 100
            filters:
                central_crop: { size: [770, 230] }

        goal_list_vertical:
            quality: 100
            filters:
                central_crop: { size: [370, 540] }

        goal_list_big:
            quality: 100
            filters:
                central_crop: { size: [770, 540] }

        goal_admin_list:
            quality: 100
            filters:
                central_crop: { size: [90, 90] }

        goal_slider_image:
            quality: 100
            filters:
                thumbnail: { size: [780, 435], mode: inset }

        goal_bucketlist:
            quality: 100
            filters:
                central_crop: { size: [320, 180] }

        goal_cover:
            quality: 100
            filters:
                central_crop: { size: [1280, 680] }

        user_cover:
            quality: 100
            filters:
                central_crop: { size: [1280, 274] }

        user_image:
            quality: 100
            filters:
                central_crop: { size: [140, 140] }

        user_icon:
            quality: 100
            filters:
                central_crop: { size: [60, 60] }

        goal_bg:
            quality: 80
            filters:
                thumbnail: { size: [1280, 720], mode: outbound }

knp_markdown:
    parser:
        service: markdown.parser.max

mobile_detect:
    redirect:
        mobile: ~
        tablet: ~
    switch_device_view: ~


rms_push_notifications:
  android:
      timeout: 60 # Seconds to wait for connection timeout, default is 5
      gcm:
          api_key: "%android_api%" # This is titled "Server Key" when creating it
  ios:
      timeout: 60 # Seconds to wait for connection timeout, default is 60
      sandbox: false
#      pem: %kernel.root_dir%/Certificates/luvbyrdDev.pem
      pem: %kernel.root_dir%/Certificates/luvbyrdProd.pem
#      passphrase: %kernel.root_dir%/Certificates/Certificates_dev.p12

genemu_form:
    select2:
        enabled: true
        configs:
            width: 100%
            allowClear: false
            minimumInputLength: 0

monolog:
    channels: ["mailchimp", "mandrill"]
    handlers:
        mailchimp:
            type:  stream
            path:  "%kernel.logs_dir%/mailchimp.log"
            channels: [mailchimp]
        mandrill:
            type:  stream
            path:  "%kernel.logs_dir%/mandrill.log"
            channels: [mandrill]