imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    languages:
        en: en
        ru: ru
    tablet:
        with: 640
        height: 640
    mobile:
        with: 480
        height: 320
    list:
        with: 770
        height: 540
    cover:
        with: 1280
        height: 720

framework:
    #esi:             ~
    translator:      { fallbacks: ["%locale%"] }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    #serializer:      { enable_annotations: true }
    templating:
        engines: ['twig']
        assets_version: v163
        #assets_version: SomeVersionScheme
    default_locale:  en
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
        gc_probability: 0
        save_path: ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources: [ 'AppBundle:Form:multipleFile.html.twig', 'AppBundle:Form:location.html.twig', 'AppBundle:Form:multipleVideo.html.twig', 'A2lixTranslationFormBundle::default.html.twig']

    globals:
        project_name: %project_name%


# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [ AppBundle, FOSCommentBundle]
    #java: /usr/bin/java
    filters:
        cssrewrite: ~
        less:
            node: /usr/local/bin/node
            node_paths: [/usr/local/lib/node_modules]
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor-2.4.7.jar"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        entity_listener_resolver: bl.settings.listener.resolver
        dql:
            datetime_functions:
                date:           Oro\ORM\Query\AST\Functions\SimpleFunction
            numeric_functions:
                timestampdiff:  Oro\ORM\Query\AST\Functions\Numeric\TimestampDiff
        filters:
            # An array of filters
            publish_filter:
                class:                AppBundle\Filter\PublishFilter
                enabled:              false

        mappings:
            loggable:
                type: annotation
                alias: Gedmo
                prefix: Gedmo\Loggable\Entity
                dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }


#    fos user bundle
fos_user:
    service:
        mailer: bl.user.mailer
    db_driver: orm # other valid values are 'mongodb', 'couchdb' and 'propel'
    firewall_name: main
    user_class: Application\UserBundle\Entity\User
    registration:
            form:
                type: bl_user_registration
                handler: bl_user.form.handler.registration
    resetting:
        email:
            template: FOSUserBundle:Resetting:email.html.twig

# fos comment bundle
fos_comment:
    db_driver: orm
    class:
        model:
            comment: Application\CommentBundle\Entity\Comment
            thread: Application\CommentBundle\Entity\Thread
    service:
        sorting:
            default: date_asc

# fos rest bundle
fos_rest:
    param_fetcher_listener: true
    body_listener: false
    body_converter:
                enabled: true
    format_listener: false
    view:
        view_response_listener: true
    routing_loader:
        default_format: json
        include_format: false

#    hwi oauth configs
hwi_oauth:
    firewall_name: main
    resource_owners:
            facebook:
                type:                facebook
                client_id:           "%facebook_client_id%"
                client_secret:       "%facebook_client_secret%"
                scope:               "public_profile user_friends email"
                infos_url:           "https://graph.facebook.com/me?fields=id,email,first_name,last_name,gender,birthday,picture"
            google:
                type:                google
                client_id:           "%google_client_id%"
                client_secret:       "%google_client_secret%"
                scope:               "email profile"
            twitter:
                type:                twitter
                client_id:           "%twitter_client_id%"
                client_secret:       "%twitter_client_secret%"

# sonata block configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.admin.block.search_result:
            contexts: [admin]

        sonata.block.service.text:
        sonata.block.service.action:
        sonata.block.service.rss:

# sonata admin configuration
sonata_admin:
    dashboard:
        blocks:
            # display a dashboard block
            - { position: left, type: sonata.admin.block.admin_list }

# stfo doctrine extensions
stof_doctrine_extensions:
    default_locale: en
    translation_fallback: true
    orm:
        default:
            timestampable: true
            sluggable: true
            translatable: true
            loggable: true

# tinumce
stfalcon_tinymce:
    include_jquery:       false
    tinymce_jquery:       false
    language: en
    theme:
          # Simple theme: same as default theme
          simple:
               plugins:
                   - "advlist autolink lists link image charmap print preview hr anchor pagebreak"
                   - "searchreplace wordcount visualblocks visualchars code fullscreen"
                   - "insertdatetime media nonbreaking save table contextmenu directionality"
                   - "emoticons template paste textcolor"
               toolbar1: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
               toolbar2: "print preview media | forecolor backcolor emoticons | stfalcon | example"
               image_advtab: true

a2lix_translation_form:
    locales: [en, ru]                       # [Optionnal] Array of translations locales. Can be specified in the form.
    default_required: false

liip_imagine:
    resolvers:
       default:
          web_path: ~

    filter_sets:
        cache: ~
        goal_list_small:
            quality: 100
            filters:
                thumbnail: { size: [370, 230], mode: outbound }
                upscale: { min: [370, 230] }
                central_crop: { size: [370, 230] }

        goal_list_horizontal:
            quality: 100
            filters:
                thumbnail: { size: [770, 230], mode: outbound }
                upscale: { min: [770, 230] }
                central_crop: { size: [770, 230] }

        goal_list_vertical:
            quality: 100
            filters:
                thumbnail: { size: [370, 540], mode: outbound }
                upscale: { min: [370, 540] }
                central_crop: { size: [370, 540] }

        goal_list_big:
            quality: 100
            filters:
                thumbnail: { size: [770, 540], mode: outbound }
                upscale: { min: [770, 540] }
                central_crop: { size: [770, 540] }

        goal_bucketlist:
            quality: 100
            filters:
                thumbnail: { size: [320, 180], mode: outbound }
                upscale: { min: [320, 180] }
                central_crop: { size: [320, 180] }

        goal_cover:
            quality: 100
            filters:
                thumbnail: { size: [1280, 680], mode: outbound }
                upscale: { min: [1280, 680] }
                central_crop: { size: [1280, 680] }

        user_cover:
            quality: 100
            filters:
                thumbnail: { size: [1280, 274], mode: outbound }
                upscale: { min: [1280, 274] }
                central_crop: { size: [1280, 274] }

        user_image:
            quality: 100
            filters:
                thumbnail: { size: [140, 140], mode: outbound }
                upscale: { min: [140, 140] }
                central_crop: { size: [140, 140] }

        user_icon:
            quality: 100
            filters:
                thumbnail: { size: [50, 50], mode: outbound }
                upscale: { min: [50, 50] }
                central_crop: { size: [50, 50] }

knp_markdown:
    parser:
        service: markdown.parser.max

