application_comment:
    resource: "@ApplicationCommentBundle/Controller/"
    type:     annotation

application_user:
    resource: "@ApplicationUserBundle/Controller/"
    type:     annotation

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

# fos user routes
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

#sonata user bundle routes
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

# hwi routes
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login

facebook_login:
    pattern: /login/check-facebook

google_login:
    pattern: /login/check-google

twitter_login:
    pattern: /login/check-twitter

# for fos comment
fos_comment_api:
    type: rest
    resource: "@FOSCommentBundle/Resources/config/routing.yml"
    prefix: /api
    defaults: { _format: html }

# PrestaSitemapBundle routing enable
PrestaSitemapBundle:
    resource: "@PrestaSitemapBundle/Resources/config/routing.yml"
    prefix:   /

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc/

# custom rests
app_user_goal_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\UserGoalController
    prefix:   /

app_goal_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\GoalController
    prefix:   /

app_new_feed_rest:
    type:     rest
    resource: AppBundle\Controller\Rest\NewsFeedController
    prefix:   /

app_emails_remove_rest:
    type:     rest
    resource: @ApplicationUserBundle/Controller/Rest/SettingsController.php
    prefix:   /

application_user_rest:
    type:     rest
    resource: @ApplicationUserBundle/Controller/Rest/UserController.php

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.xml"


