security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        hwi_oauth_user_provider:
            id: hwi_oauth.user.provider
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN, ROLE_SONATA_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                success_handler: authentication_handler
                failure_handler: authentication_handler
                default_target_path: /
            anonymous: true
            logout:
                path:   /logout
                target: /
            oauth:
                resource_owners:
                    facebook:           /login/check-facebook
                    google:             /login/check-google
                    twitter:            /login/check-twitter
                success_handler: authentication_handler
                failure_handler: authentication_handler
                default_target_path: /
                login_path:        /check-login
                failure_path:      /check-login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/admin(.*), role: [ROLE_ADMIN, ROLE_SONATA_ADMIN] }
