<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends EntityRepository
{
    /**
     * @param $first
     * @param $count
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findLastUpdated($first, $count)
    {
       $data = $this->getEntityManager()
            ->createQuery("SELECT b.updated 
                           FROM AppBundle:Blog b
                           ORDER BY b.updated DESC
                           ")
            ->setFirstResult($first)
            ->setMaxResults($count)
            ->getResult();

        $data = reset($data);
        return $data['updated'];
    }

    /**
     * @param $first
     * @param $count
     * @return mixed
     * @return array
     */
    public function findAllBlogForMobile($first, $count)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT b 
                           FROM AppBundle:Blog b
                           ORDER BY b.created DESC
                           ")
            ->setFirstResult($first)
            ->setMaxResults($count)
            ->getResult();
    }

    /**
     * @return mixed
     * @return array
     */
    public function findAllBlog()
    {
        return $this->getEntityManager()
            ->createQuery("SELECT b 
                           FROM AppBundle:Blog b
                           ORDER BY b.created DESC
                           ")
            ->getResult();
    }
}
