<?php

namespace AppBundle\Entity\Repository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogRepository extends \Doctrine\ORM\EntityRepository
{
    public function findLastUpdated()
    {
       $data = $this->getEntityManager()
            ->createQuery("SELECT b.updated 
                           FROM AppBundle:Blog b
                           ORDER BY b.updated DESC
                           ")
            ->setMaxResults(1)
            ->getOneOrNullResult();
        
        return $data['updated'];
    }
}
