<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Controller\Rest\StatisticPageController;
use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    /**
     * @param $start
     * @param $end
     * @param $groupBy
     * @return array
     */
    public function findStatisticData($start, $end, $groupBy)
    {
        //get emails statistic count
        $emails =  $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(em.id) as cnt, em.sent as created, SUM(CASE WHEN em.seen IS NOT NULL THEN 1 ELSE 0 END) as seen')
            ->from('AppBundle:Email', 'em')
            ->groupBy('em.sent')
            ->orderBy('em.sent');

//        //check if groupBy is month
//        if ($groupBy == StatisticPageController::MONTH) {
//            $emails
//                ->andWhere('em.sent = month(em.sent)')
//                ->setParameter('month', $start);
//        }

        //if start date is exists
        if ($start) {

            $emails
                ->andWhere(':start <= date(em.sent)')
                ->setParameter('start', $start);
        }

        //if end date is exists
        if ($end) {

            $emails
                ->andWhere(':end >= date(em.sent)')
                ->setParameter('end', $end);
        }

        //get counts for emails
        $emails = $emails->getQuery()->getResult();

        return $emails;
    }
}
