<?php

namespace AppBundle\Entity\Repository;

use AppBundle\Controller\Rest\StatisticController;
use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    /**
     * @param $start
     * @param $end
     * @param $groupBy
     * @return array
     */
    public function findStatisticData($groupBy = StatisticController::DAY, $start, $end)
    {
        //get emails statistic count
        $emails =  $this->getEntityManager()
            ->createQueryBuilder()
            ->select('count(em.id) as send, em.sent as created, SUM(CASE WHEN em.seen IS NOT NULL THEN 1 ELSE 0 END) as read')
            ->from('AppBundle:Email', 'em');

        //if start date is exists
        if ($start) {
            $emails
                ->andWhere(':start <= date(em.sent)')
                ->setParameter('start', $start);
        }

        //if end date is exists
        if ($end) {
            $emails
                ->andWhere(':end >= date(em.sent)')
                ->setParameter('end', $end);
        }

        // switch for group by
        switch($groupBy) {

            case StatisticController::DAY:
                $emails
                    ->addSelect('day(em.sent) as hidden day')
                    ->groupBy('day')
                    ->orderBy('day');
                break;
            case StatisticController::WEEK:
                $emails
                    ->addSelect('dayofweek(em.sent) as hidden wk')
                    ->groupBy('wk')
                    ->orderBy('wk');
                break;
            case StatisticController::MONTH:
                $emails
                    ->addSelect('month(em.sent) as hidden mn')
                    ->groupBy('mn')
                    ->orderBy('mn');
                break;
            default:
                break;
        }

        //get counts for emails
        $emails = $emails->getQuery()->getResult();

        return $emails;
    }
}
