<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GoalImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalImageRepository extends EntityRepository
{
    /**
     * @param $ids
     * @return array
     */
    public function findByIDs($ids)
    {
        $query =  $this->getEntityManager()
            ->createQuery(" SELECT i
                            FROM AppBundle:GoalImage i
                            WHERE i.id in (:ids)
                            ")
            ->setParameter('ids', $ids)
            ->getResult()
        ;

        return $query;
    }

    /**
     * @return array
     */
    public function findAllOlder()
    {
        $query =  $this->getEntityManager()
            ->createQuery(" SELECT i
                            FROM AppBundle:GoalImage i
                            LEFT JOIN i.goal g
                            WHERE g.id is null and g.updated < :myDate
                            ")
            ->setParameter('myDate', new \DateTime('-1 days'))
            ->getResult()
        ;

        return $query;
    }
}
