<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    /**
     * This function is used to get all places by goal ids
     * 
     * @param $goalIds array
     * @return array
     */
    public function findPlaceByGoalIds($goalIds)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT DISTINCT p
                           FROM AppBundle:Place p
                           JOIN p.goal g
                           WHERE g.id in (:goalIds)")
            ->setParameter('goalIds', $goalIds)
            ->getResult();
    }

    /**
     * This function is used to get all places by names and related status
     *
     * @param $places array
     * @param $userId integer
     * @return array
     */
    public function findByNamesAndUserId($places, $userId)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT p, (CASE WHEN ur.id = :userId THEN 1 ELSE 0 END) AS related
                           FROM AppBundle:Place p
                           LEFT JOIN p.userPlace up
                           LEFT JOIN up.user ur
                           WHERE p.name in (:places)
                           ")
            ->setParameter('userId', $userId)
            ->setParameter('places', $places)
            ->getResult();
    }
}
