<?php

namespace AppBundle\Entity\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends EntityRepository
{
    /**
     * This function is used to get goal by place
     *
     * @param $place
     * @return mixed
     * @throws \Doctrine\ORM\NonUniqueResultException
     */
    public function findGoalByPlace($place)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT g as goal, u.id as user_id, u.uId as u_id
                           FROM AppBundle:Goal g
                           LEFT JOIN g.place p
                           LEFT JOIN g.userGoal ug
                           LEFT JOIN ug.user u
                           WHERE p.name in (:place)")
            ->setParameter('place', $place)
            ->getResult();
    }
}
