<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuccessStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuccessStoryRepository extends EntityRepository
{
    /**
     * @param $ids
     * @return array|null
     */
    public function findByIdsWithRelations($ids)
    {
        if (!count($ids)){
            return null;
        }

        return $this->getEntityManager()
            ->createQuery("SELECT ss, goal, u
                           FROM AppBundle:SuccessStory ss
                           INDEX BY ss.id
                           JOIN ss.goal goal
                           JOIN ss.user u
                           WHERE ss.id IN (:ssIds)")
            ->setParameter('ssIds', $ids)
            ->getResult();
    }
}
