<?php

namespace AppBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * SuccessStoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SuccessStoryRepository extends EntityRepository
{
    /**
     * @param $userId
     * @param $goalId
     * @return array
     */
    public function findUserGoalStory($userId, $goalId)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT ss, i
                           FROM AppBundle:SuccessStory ss
                           JOIN ss.goal g WITH g.id = :goalId
                           JOIN ss.user u WITH u.id = :userId
                           LEFT JOIN ss.files i")
            ->setParameter('userId', $userId)
            ->setParameter('goalId', $goalId)
            ->setFirstResult(0)
            ->getResult();
    }
}
