<?php

namespace Application\AffiliateBundle\Entity\Repository;

/**
 * AffiliateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AffiliateRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $pageLink
     * @return array
     */
    public function getAffiliatesByLink($pageLink)
    {
        return $this->getEntityManager()
            ->createQuery("SELECT a
                           FROM ApplicationAffiliateBundle:Affiliate a
                           WHERE a.links LIKE :pageLink")
            ->setParameter('pageLink', '%' . $pageLink . '%')
            ->getResult();
    }
}
