services:

    application_affiliate.admin.affiliate:
        class: Application\AffiliateBundle\Admin\AffiliateAdmin
        arguments: [~, Application\AffiliateBundle\Entity\Affiliate, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: group_name_general, label: Affiliate }
