<?php

namespace Application\CommentBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends EntityRepository
{
    /**
     * @param $threadId
     * @param null $first
     * @param null $count
     * @return array
     */
    public function findThreadComments($threadId, $first = null, $count = null)
    {
        $query = $this->getEntityManager()
            ->createQuery("SELECT cmt, a
                           FROM ApplicationCommentBundle:Comment cmt
                           LEFT JOIN cmt.author a
                           WHERE cmt.thread = :threadId")
            ->setParameter('threadId', $threadId);

        if (is_numeric($first) && is_numeric($count)){
            $query
                ->setFirstResult($first)
                ->setMaxResults($count);
        }

        return $query->getResult();
    }
}

