services:
    app.admin.goal:
        class: AppBundle\Admin\GoalAdmin
        arguments: [~, AppBundle\Entity\Goal, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Goal }

    app.admin.moderator_goal:
        class: AppBundle\Admin\ModeratorGoalAdmin
        arguments: [~, AppBundle\Entity\Goal, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Goal }
